[package]
name = "dds_recon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
pretty_env_logger = "0.4.0"
rustdds = "0.7.10"
